# Generated by Django 5.2.4 on 2026-01-14 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_kcal', models.FloatField(blank=True, null=True, verbose_name='칼로리(kcal)')),
                ('carbs_g', models.FloatField(blank=True, null=True, verbose_name='탄수화물(g)')),
                ('protein_g', models.FloatField(blank=True, null=True, verbose_name='단백질(g)')),
                ('fat_g', models.FloatField(blank=True, null=True, verbose_name='지방(g)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='posts.post')),
            ],
        ),
    ]
