# Generated by Django 5.2.4 on 2026-01-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_nutritioninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.CharField(default='', max_length=20, verbose_name='해시태그'),
            preserve_default=False,
        ),
    ]
