# Generated by Django 5.2.4 on 2026-01-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.CharField(max_length=20, null=True, verbose_name='해시태그'),
        ),
    ]
