# Generated by Django 6.0 on 2025-12-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('ACTION', '액션'), ('COMEDY', '코미디'), ('DRAMA', '드라마'), ('ROMANCE', '로맨스'), ('THRILLER', '스릴러'), ('HORROR', '공포'), ('SF', 'SF'), ('FANTASY', '판타지'), ('ANIMATION', '애니메이션'), ('DOCUMENTARY', '다큐멘터리')], max_length=20),
        ),
    ]
