# Generated by Django 6.0.1 on 2026-01-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('액션', '액션'), ('코미디', '코미디'), ('드라마', '드라마'), ('로맨스', '로맨스'), ('스릴러', '스릴러'), ('공포', '공포'), ('SF', 'SF'), ('판타지', '판타지'), ('애니메이션', '애니메이션'), ('다큐멘터리', '다큐멘터리')], max_length=20),
        ),
    ]
