# Generated by Django 5.2.4 on 2026-01-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_from_tmdb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
