# Generated by Django 6.0.1 on 2026-01-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_is_from_tmdb_review_tmdb_id_alter_review_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tmdb_poster_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user_poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
